### ISSUE TITLE
Cannot read property 'loggedUser' of undefined

### ISSUE THREAD

**Issue by cfpwastaken** [loumadev/EdupageAPI#5] opened 2021-09-15 15:20 UTC
I tried logging in but it prints this stacktrace:
`TypeError: Cannot read property 'loggedUser' of undefined
    at new ASC (node_modules\edupage-api\src\ASC.js:31:36)
    at Edupage.refreshEdupage (node_modules\edupage-api\src\Edupage.js:220:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Edupage.refresh (node_modules\edupage-api\src\Edupage.js:182:3)
    at async node_modules\edupage-api\src\Edupage.js:169:5`

Affected line:
`this.loggedUser = data.req_props.loggedUser;`

Causes:
data is {}

**Comment by loumadev** [comment] 2021-09-15 21:49
Hello,
thank you for reporting this error.
It's important to keep the API compatible with all kinds of Edupage configurations.

Please update the [EdupageAPI](https://github.com/loumadev/EdupageAPI/releases/tag/v0.7.7) by `npm update edupage-api`. There's added handling for this kind of errors.
Run your code once again, so error log could get generated and then post it here in the comments (do not forget crash log file) so I can get closer look on what is causing this error.

**Comment by cfpwastaken** [comment] 2021-09-16 13:25
Hello!
Liking the new error system so far.
Console: https://hastebin.com/utakeqoyoy.apache
Error log:
`{
	"error": {},
	"data": {
		"html": "Requested url was not found on this server!"
	}
}`

Seems like there is some url typo or smh?

**Comment by loumadev** [comment] 2021-09-16 17:37
Thanks for the response.

After some research, why is this happing, I realized that `undefined.edupage.org` returns exactly what you reported. Therefore, I assume the problem is in logging in and auto-detecting Edupage origin.

I released a [new version](https://github.com/loumadev/EdupageAPI/releases/tag/v0.7.8) with even more error logging stuff, so we can better see what is going on.

Please update the package, run it again and post new errors.
Thank you for cooperating.

**Comment by cfpwastaken** [comment] 2021-09-17 12:10
Console: https://hastebin.com/qahelazufe.apache
Error Log: https://hastebin.com/danobupaqa.json

**Comment by cfpwastaken** [comment] 2021-09-17 12:11
>  I realized that undefined.edupage.org returns exactly what you reported. 

Maybe add a "origin" parameter to the login function like
login("Username", "Password", "School domain here")

**Comment by ivanhrabcak** [comment] 2021-09-17 12:12
That is what I've proposed in #2!

**Comment by cfpwastaken** [comment] 2021-09-17 12:33
Oh didn't see, sorry. But yeah this should prob be the way to go.

EduPage is such a mess

**Comment by loumadev** [comment] 2021-09-17 14:11
Thank you, @ivanhrabcak, for pointing this out in #2.

You might be right, but firstly, it's quite a big limitation, so I really want to avoid that approach. Next, from the data you posted, there must be some other issue with this. I hoped the error will be thrown in [login method](https://github.com/loumadev/EdupageAPI/blob/master/src/User.js#L220-L224) (like invalid redirect school subdomain (origin, as I call it)), but surprisingly, the error appeared after trying to request `/user` endpoint. This means the login server, `portal.edupage.org`, has logged the user in correctly, with valid redirect URL, but probably malformed subdomain (origin), so the problem is somewhere in between. There might be some more login steps to successfully complete the login process.

@cfpwastaken, it would be very helpful if I could have access to your account where I could debug the login process step by step, so I could find the issue and potentially fix it.
@ivanhrabcak, do you have any experience with it? Have you already tried it? So I don't have to waste the time.

**Comment by cfpwastaken** [comment] 2021-09-17 14:16
> if I could have access to your account where I could debug the login process step by step, so I could find the issue and potentially fix it.

No i can't really give my account creds out because. Well. It's from my school account, anyone could be doin some nasty stuff there and my teachers would kill me in the end. So that wont happen sadly

**Comment by ivanhrabcak** [comment] 2021-09-17 14:36
I think it would be best if we met on my [Edupage discord server](https://discord.gg/yrBWDGzGeZ) and solve the issue. Do you have time tomorrow? We can arrange a time on the server if you want.

**Comment by cfpwastaken** [comment] 2021-09-17 17:21
Me or @loumadev ?

**Comment by loumadev** [comment] 2021-09-17 17:38
> > if I could have access to your account where I could debug the login process step by step, so I could find the issue and potentially fix it.
> 
> No i can't really give my account creds out because. Well. It's from my school account, anyone could be doin some nasty stuff there and my teachers would kill me in the end. So that wont happen sadly

I know, I don't want you to just share your private credentials on the internet. I was thinking about some remote desktop software or something like that.



> I think it would be best if we met on my [Edupage discord server](https://discord.gg/yrBWDGzGeZ) and solve the issue. Do you have time tomorrow? We can arrange a time on the server if you want.

Yes, I agree, this would be awesome.



> Me or @loumadev ?

Both of us.

**Comment by cfpwastaken** [comment] 2021-09-17 17:51
Okay what time? And what time differs do we have?

**Comment by cfpwastaken** [comment] 2021-09-17 17:51
Its 19:51 (about 20:00) for me in Germany right now

**Comment by loumadev** [comment] 2021-09-17 18:13
I assume we all live in the same time zone.

**Comment by cfpwastaken** [comment] 2021-09-17 18:21
Amazing but what time we doin that then? I should have time around 17

**Comment by ivanhrabcak** [comment] 2021-09-17 18:30
Tomorrow at 17 is good for me.

**Comment by loumadev** [comment] 2021-09-17 18:50
Ok, so tomorrow at 17 on @ivanhrabcak's discord server.

**Comment by cfpwastaken** [comment] 2021-09-18 08:17
Okay. If you guys find time rn we can do it rn too

**Comment by loumadev** [comment] 2021-09-19 19:21
For further readers:
* After some debugging, we were finally able to fix the bug which was causing issues with logging in (the problem was with hyphen `-` in school origin).
* We also found another bug (not listed in the issues here), where user IDs were negative, but it got fixed quickly.

Thank you both @cfpwastaken and @ivanhrabcak for making some time to fix those bugs. I'm closing this and #2 issues since they were related.

**Closed as completed** 2021-09-19 19:21 UTC
Labels: 🐛bug
